export const catBreeds = [
    "Ragdoll",
    "Siberian",
    "Persian",
    "British shorthair",
    "Abyssinian",
    "Scottish fold",
    "Sphynx",
    "Devon Rex",
    "American shorthair",
    "Bengal",
    "Russian blue",
    "Siamese",
    "Cornish rex",
    "Selkirk rex",
    "Birman",
    "Aegean",
    "Asian",
    "Chausie",
    "Ocicat",
    "Manx"
]



// export const catBreeds = [
//     "Abyssinian",
//     "Aegean",
//     "American Bobtail",
//     "American Curl",
//     "American Ringtail",
//     "American Shorthair",
//     "American Wirehair",
//     "Aphrodite Giant",
//     "Arabian Mau",
//     "Asian",
//     "Asian Semi-longhair",
//     "Australian Mist",
//     "Balinese",
//     "Bambino",
//     "Bengal",
//     "Birman",
//     "Bombay",
//     "Brazilian Shorthair",
//     "British Longhair",
//     "British Shorthair",
//     "Burmese",
//     "Burmilla",
//     "California Spangled",
//     "Chantilly-Tiffany",
//     "Chartreux",
//     "Chausie",
//     "Colorpoint Shorthair",
//     "Cornish Rex",
//     "Cymric",
//     "Cyprus",
//     "Devon Rex",
//     "Donskoy/Don Sphynx",
//     "Dragon Li/Chinese Li Hua",
//     "Dwelf",
//     "Egyptian Mau",
//     "European Shorthair",
//     "Exotic Shorthair",
//     "Foldex",
//     "German Rex", 
//     "Havana Brown",
//     "Highlander",
//     "Himalayan",
//     "Japanese Bobtail",
//     "Javanese",
//     "Kanaani",
//     "Khao Manee",
//     "Kinkalow",
//     "Korat",
//     "Korean Bobtail",
//     "Kornja",
//     "Kurilian Bobtail",
//     "Lambkin",
//     "LaPerm",
//     "Lykoi",
//     "Maine Coon",
//     "Manx",
//     "Mekong Bobtail",
//     "Minskin",
//     "Minuet",
//     "Munchkin",
//     "Nebelung",
//     "Norwegian Forest",
//     "Ocicat",
//     "Ojos Azules",
//     "Oriental Bicolor",
//     "Oriental Longhair",
//     "Oriental Shorthair",
//     "Persian",
//     "Peterbald",
//     "Pixie-bob",
//     "Ragamuffin",
//     "Ragdoll",
//     "Raas",
//     "Russian Blue",
//     "Russian White/Black/Tabby",
//     "Sam Sawet",
//     "Savannah",
//     "Scottish Fold Cat",
//     "Selkirk Rex",
//     "Serengeti",
//     "Serrade Petit",
//     "Siamese",
//     "Siberian",
//     "Singapura",
//     "Snowshoe",
//     "Sokoke",
//     "Somali",
//     "Sphynx",
//     "Suphalak",
//     "Thai",
//     "Thai Lilac",
//     "Tonkinese",
//     "Toybob",
//     "Toyger",
//     "Turkish Angora",
//     "Turkish Van",
//     "Turkish Vankedisi",
//     "Ukranian Levkoy",
//     "York Chocolate"
// ]
